# Generated by Django 4.2.7 on 2023-11-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_sold',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='contingentListingType',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='dateSold',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='detailUrl',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='property',
            name='listingStatus',
            field=models.CharField(default='FOR_SALE', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='property',
            name='lotAreaValue',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='priceChange',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='propertyType',
            field=models.CharField(default='SINGLE_FAMILY', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='variableData',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='zestimate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='zpid',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
