# Generated by Django 4.2.7 on 2023-11-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_description_remove_property_is_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
