# Generated by Django 4.2.7 on 2023-11-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_favorite',
        ),
    ]
