# Generated by Django 4.2.7 on 2023-11-12 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
