# Generated by Django 4.2.7 on 2023-11-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
