# Generated by Django 4.2.7 on 2023-11-14 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0008_alter_property_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='contingentListingType',
        ),
        migrations.RemoveField(
            model_name='property',
            name='dateSold',
        ),
        migrations.RemoveField(
            model_name='property',
            name='detailUrl',
        ),
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='listingStatus',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lotAreaValue',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='priceChange',
        ),
        migrations.RemoveField(
            model_name='property',
            name='propertyType',
        ),
        migrations.RemoveField(
            model_name='property',
            name='variableData',
        ),
        migrations.RemoveField(
            model_name='property',
            name='zestimate',
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='property',
            name='zpid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
